# Generated by Django 2.0.5 on 2018-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=50)),
                ('grades', models.CharField(max_length=100)),
            ],
        ),
    ]
