# Generated by Django 2.0.5 on 2018-08-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('grade_time', models.DateTimeField(default=datetime.datetime(2018, 8, 23, 15, 46, 0, 930846))),
            ],
        ),
    ]
