# Generated by Django 2.0.5 on 2018-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_auto_20180827_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade_time',
            field=models.CharField(max_length=50),
        ),
    ]
