# Generated by Django 2.0.5 on 2018-08-31 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20180831_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade_day',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
