# Generated by Django 2.0.5 on 2018-09-01 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0009_auto_20180831_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('grade_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_time', models.CharField(max_length=50)),
                ('classroom_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
