# Generated by Django 2.0.5 on 2018-09-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0010_auto_20180902_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradelog',
            name='grade_day',
        ),
    ]
