# Generated by Django 2.0.5 on 2018-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0012_gradelog_grade_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grades',
            field=models.CharField(max_length=258),
        ),
    ]
