# Generated by Django 2.0.5 on 2018-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0013_auto_20180912_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(),
        ),
    ]
