# Generated by Django 2.0.5 on 2018-09-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0015_auto_20180919_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 12, 0, 20, 285099)),
        ),
    ]
