# Generated by Django 2.0.5 on 2018-09-28 15:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0016_auto_20180924_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='attendence',
            field=models.CharField(default=django.utils.timezone.now, max_length=258),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 15, 20, 4, 101789)),
        ),
    ]
