# Generated by Django 2.0.5 on 2018-09-28 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0020_auto_20180928_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='attendance',
            field=models.CharField(default=['0'], max_length=258),
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 16, 3, 42, 456230)),
        ),
    ]
