# Generated by Django 2.0.5 on 2018-09-28 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0022_auto_20180928_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='attendance',
            field=models.CharField(default="['0', '0']", max_length=258),
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 16, 9, 30, 811092)),
        ),
    ]
