# Generated by Django 2.0.5 on 2018-09-28 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0025_auto_20180928_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 17, 35, 14, 476063)),
        ),
    ]
