# Generated by Django 2.0.5 on 2018-09-28 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0026_auto_20180928_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendances', models.CharField(max_length=258)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Grade')),
            ],
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 17, 46, 56, 884702)),
        ),
    ]
