# Generated by Django 2.0.5 on 2018-09-29 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0027_auto_20180928_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 18, 13, 7, 555450)),
        ),
    ]
