# Generated by Django 2.0.5 on 2018-10-01 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0028_auto_20180929_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grades',
            field=models.CharField(default=None, max_length=258),
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 0, 34, 38, 199725)),
        ),
    ]
