# Generated by Django 2.0.5 on 2018-10-01 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0029_auto_20181001_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grades',
            field=models.CharField(default='[-1]', max_length=258),
        ),
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 0, 35, 45, 778396)),
        ),
    ]
