# Generated by Django 2.0.5 on 2018-10-01 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0030_auto_20181001_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 53, 54, 358637)),
        ),
    ]
