# Generated by Django 2.0.5 on 2018-10-14 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0031_auto_20181001_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 3, 27, 858048)),
        ),
    ]
