# Generated by Django 2.0.5 on 2018-10-15 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0032_auto_20181014_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 1, 46, 23, 127622)),
        ),
    ]
