# Generated by Django 2.0.5 on 2018-10-15 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0034_auto_20181015_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
