# Generated by Django 2.0.5 on 2018-11-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0035_auto_20181015_0154'),
        ('grade', '0033_auto_20181028_0528'),
    ]

    operations = [
    ]
