# Generated by Django 2.0.5 on 2018-11-08 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0036_merge_20181105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='grade_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
