# Generated by Django 2.0.5 on 2018-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0037_auto_20181108_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelog',
            name='classroom_id',
            field=models.CharField(max_length=500),
        ),
    ]
